apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dotnet-role
  namespace: bermtec
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  # Add more rules as needed for other resources and verbs
